"""add district and google_maps_url to properties

Revision ID: 57ab3c1f1bc8
Revises: a0778b49106d
Create Date: 2026-03-23 00:33:36.205783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57ab3c1f1bc8'
down_revision: Union[str, None] = 'a0778b49106d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
