import io
from datetime import date
from decimal import Decimal

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle


def _fmt_currency(val) -> str:
    if val is None:
        return "$0"
    return f"${float(val):,.2f}"


def _fmt_date(d) -> str:
    if isinstance(d, date):
        return d.strftime("%B %d, %Y")
    return str(d) if d else ""


def _fmt_pct(val) -> str:
    if val is None:
        return "0%"
    return f"{float(val):.2f}%"


def generate_loan_agreement(
    deal_number: str,
    principal: Decimal,
    interest_rate: Decimal,
    term_months: int,
    start_date: date,
    maturity_date: date,
    origination_fee_pct: Decimal,
    origination_fee_amount: Decimal,
    borrower_name: str,
    investor_name: str,
    property_address: str,
    property_type: str,
    ltv: Decimal,
    language: str = "en",
) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=letter, topMargin=0.75 * inch, bottomMargin=0.75 * inch)
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle("Title", parent=styles["Title"], fontSize=16, spaceAfter=20)
    heading_style = ParagraphStyle("Heading", parent=styles["Heading2"], fontSize=12, spaceAfter=10, spaceBefore=15)
    body_style = ParagraphStyle("Body", parent=styles["Normal"], fontSize=10, spaceAfter=8, leading=14)

    elements = []

    # Title
    elements.append(Paragraph(f"Loan Agreement — {deal_number}", title_style))
    elements.append(Paragraph("Lender.cr — Private Lending Marketplace", styles["Normal"]))
    elements.append(Spacer(1, 20))

    # Parties
    elements.append(Paragraph("1. Parties", heading_style))
    elements.append(Paragraph(f"<b>Borrower:</b> {borrower_name}", body_style))
    elements.append(Paragraph(f"<b>Investor/Lender:</b> {investor_name}", body_style))
    elements.append(Paragraph("<b>Platform:</b> Lender.cr", body_style))

    # Loan Terms
    elements.append(Paragraph("2. Loan Terms", heading_style))
    terms_data = [
        ["Principal Amount", _fmt_currency(principal)],
        ["Interest Rate (Monthly)", _fmt_pct(interest_rate)],
        ["Interest Rate (Annual)", _fmt_pct(float(interest_rate) * 12)],
        ["Term", f"{term_months} months"],
        ["Start Date", _fmt_date(start_date)],
        ["Maturity Date", _fmt_date(maturity_date)],
        ["LTV at Origination", _fmt_pct(ltv)],
        ["Origination Fee", f"{_fmt_pct(origination_fee_pct)} ({_fmt_currency(origination_fee_amount)})"],
        ["Payment Type", "Interest-only with balloon principal at maturity"],
    ]
    t = Table(terms_data, colWidths=[2.5 * inch, 4 * inch])
    t.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("LINEBELOW", (0, 0), (-1, -1), 0.5, colors.lightgrey),
    ]))
    elements.append(t)

    # Collateral
    elements.append(Paragraph("3. Collateral Property", heading_style))
    elements.append(Paragraph(f"<b>Type:</b> {property_type}", body_style))
    elements.append(Paragraph(f"<b>Address:</b> {property_address}", body_style))

    # Legal
    elements.append(Paragraph("4. Legal Framework", heading_style))
    elements.append(Paragraph(
        "This loan is secured by a first-position mortgage (hipoteca) registered at the Registro Nacional de la Propiedad of Costa Rica. "
        "The borrower agrees to maintain the property in good condition and to pay all property taxes during the term of the loan.",
        body_style,
    ))

    # Signatures
    elements.append(Spacer(1, 40))
    elements.append(Paragraph("5. Signatures", heading_style))
    elements.append(Spacer(1, 30))
    sig_data = [
        ["_" * 40, "", "_" * 40],
        [borrower_name, "", investor_name],
        ["Borrower", "", "Investor/Lender"],
    ]
    sig = Table(sig_data, colWidths=[2.5 * inch, 1 * inch, 2.5 * inch])
    sig.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("TOPPADDING", (0, 0), (-1, -1), 2),
    ]))
    elements.append(sig)

    elements.append(Spacer(1, 20))
    elements.append(Paragraph(
        f"Generated by Lender.cr on {date.today().strftime('%B %d, %Y')}. "
        "This document is for informational purposes and should be reviewed by legal counsel before signing.",
        ParagraphStyle("Small", parent=styles["Normal"], fontSize=8, textColor=colors.grey),
    ))

    doc.build(elements)
    return buf.getvalue()


def generate_payment_schedule_pdf(
    deal_number: str,
    payments: list[dict],
) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=letter, topMargin=0.75 * inch, bottomMargin=0.75 * inch)
    styles = getSampleStyleSheet()

    elements = []
    elements.append(Paragraph(f"Payment Schedule — {deal_number}", styles["Title"]))
    elements.append(Paragraph("Lender.cr — Private Lending Marketplace", styles["Normal"]))
    elements.append(Spacer(1, 20))

    header = ["#", "Due Date", "Type", "Amount Due", "Interest", "Principal", "Servicing", "Status"]
    data = [header]

    for p in payments:
        data.append([
            str(p.get("payment_number", "")),
            _fmt_date(p.get("due_date")),
            str(p.get("payment_type", "")).replace("_", " ").title(),
            _fmt_currency(p.get("amount_due")),
            _fmt_currency(p.get("interest_portion")),
            _fmt_currency(p.get("principal_portion")),
            _fmt_currency(p.get("servicing_fee_portion")),
            str(p.get("status", "")).replace("_", " ").title(),
        ])

    t = Table(data, repeatRows=1)
    t.setStyle(TableStyle([
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1d4ed8")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#f8fafc")]),
        ("LINEBELOW", (0, 0), (-1, -1), 0.5, colors.lightgrey),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("ALIGN", (3, 0), (-1, -1), "RIGHT"),
    ]))
    elements.append(t)

    elements.append(Spacer(1, 15))
    elements.append(Paragraph(
        f"Generated by Lender.cr on {date.today().strftime('%B %d, %Y')}.",
        ParagraphStyle("Small", parent=styles["Normal"], fontSize=8, textColor=colors.grey),
    ))

    doc.build(elements)
    return buf.getvalue()
